config/routes.rb
Rails.application.routes.draw do
  root "example#input"
  get 'example/show', as: 'result'
  get 'example/show_db'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/palindrom.rb
class Palindrom < ApplicationRecord
  validates_uniqueness_of :digit, :arr, message: 'Введено не число'
  validates :digit, format: { with: /\A\d+\z/, message: 'Введите что-то' }
  before_save :set_palindrom
  def decoded_palindrom
    ActiveSupport::JSON.decode(arr)
  end

  private

  def set_palindrom
    self.arr = ActiveSupport::JSON.encode(calculate_palindrom)
  end

  def calculate_palindrom
    mas = []
    digit.times do |iter|
      mas.push(iter) if palindromis(iter) && palindromis(iter * iter)
    end
    mas
  end

  def palindromis(aaa)
    stra = aaa.to_s
    stra.reverse == stra
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/example_controller.rb
# frozen_string_literal: false

# Class for controller
class ExampleController < ApplicationController
  before_action :check, only: [:show]
  def input; end

  def show
    # @arr = palindroms(params[:digit].to_i)
    if (arr = Palindrom.find_by_digit(@digit = params[:digit]))
      @arr = arr.decoded_palindrom
    else
      arr = Palindrom.new(digit: @digit)
      if arr.save
        @arr = arr.decoded_palindrom
      else
        redirect_to root_path, notice: arr.errors.messages[:digit][0]
      end
    end
  end

  def show_db
    render xml: Palindrom.all
  end

  # private

  # def palindrom(aaa)
  #   stra = aaa.to_s
  #   stra.reverse == stra
  # end

  # def palindroms(num)
  #   mas = []
  #   num.times do |iter|
  #     mas.push(iter) if palindrom(iter) && palindrom(iter * iter)
  #   end
  #   mas
  # end

  def check
    num = params[:digit]
    if num.nil? || num.empty?
      @error = 'Empty string'
    elsif !num.match(/^\d+$/)
      @error = 'Enter numbers only'
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
  end

  def authorize
    user = User.find_by(name: params[:name])
    if user.present? && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to example_input_path
    else
      return redirect_to_login 
    end
  end

  def logout
    session[:current_user_id] = nil
    redirect_to root_path
  end

  def redirect_to_login
    redirect_to root_path, flash: { alert: 'Wrong login or password' }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/example/_error.html.erb
<div id='error-result'><%= @error %></div>

app/views/example/_result.html.erb
<h1>Результат</h1>
  <table>
    <tr>
      <th>Число</th>
      <th>Квадрат числа</th>
    </tr>
    <% @arr.each do |i| %>
    <tr>
      <td><%= i %></td>
      <td><%= i*i %></td>
    </tr>
    <% end %>
  </table>
  <h3 id = 'number-container'>Количество: <%= @arr.length %> </h3>

app/views/example/input.html.erb
<h1>Ввод числа</h1>
<h1>Привет! <%= User.find_by(id: session[:current_user_id]).name %><h1>

<%= form_with url: result_path, method: :post do |form| %>
  <%= form.label :digit, 'Число' %>
  <%= form.text_field(:digit, value: "78") %>
  <%= form.submit('Отправить', id: 'palindrom-btn') %>
<% end %>
<br>
<%= form_with url: "/session/logout", method: :get do |form| %>
  <%= form.submit('Выход', id: 'exit-btn') %>
<% end %>

<p><%= flash[:error]%></p>
<div id="result"></div>

app/views/example/show.html.erb
<h1>Результат</h1>
  <table>
    <tr>
      <th>Число</th>
      <th>Квадрат числа</th>
    </tr>
    <% @arr.each do |i| %>
    <tr>
      <td><%= i %></td>
      <td><%= i*i %></td>
    </tr>
    <% end %>
  </table>
  <h3 id = 'number-container'>Количество: <%= @arr.length %> </h3>
<%= link_to 'Вернуться на страницу ввода', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab8nt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/authorize.html.erb
<h1>Session#authorize</h1>
<p>Find me in app/views/session/authorize.html.erb</p>

app/views/session/login.html.erb
<h1>Session#login</h1>
<p>Find me in app/views/session/login.html.erb</p>
<% flash.each do |type, msg| %>
  <% unless type == "notice" %>
    <p id = 'error' class="text-danger mt-2"><%= msg %></p>
  <% end %>
<% end %>

<%= form_with url: session_authorize_path, local: true  do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div class="mt-2 d-flex align-items-center">
    <%= form.submit class: "btn btn-primary", value: 'Login' %>
    <a href="<%= new_user_path %>" class="ms-1 link text-primary">Sign Up</a>
  </div>
<% end %>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

    <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>